##Clock signal 125 MHz
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports i_clk]
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports i_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {o_leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_cs]
set_property IOSTANDARD LVCMOS33 [get_ports i_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports i_rst]
set_property IOSTANDARD LVCMOS33 [get_ports i_rx]
set_property IOSTANDARD LVCMOS33 [get_ports i_scl]
set_property IOSTANDARD LVCMOS33 [get_ports o_miso]
set_property IOSTANDARD LVCMOS33 [get_ports o_tx]
set_property IOSTANDARD LVCMOS33 [get_ports i_button]
set_property PACKAGE_PIN V13 [get_ports i_rx]
set_property PACKAGE_PIN T16 [get_ports i_rst]
set_property PACKAGE_PIN V12 [get_ports i_scl]
set_property PACKAGE_PIN W16 [get_ports o_miso]
set_property PACKAGE_PIN J15 [get_ports i_mosi]
set_property PACKAGE_PIN H15 [get_ports i_cs]
set_property PACKAGE_PIN D18 [get_ports {o_leds[3]}]
set_property PACKAGE_PIN G14 [get_ports {o_leds[2]}]
set_property PACKAGE_PIN M15 [get_ports {o_leds[1]}]
set_property PACKAGE_PIN M14 [get_ports {o_leds[0]}]
set_property PACKAGE_PIN U17 [get_ports o_tx]
set_property PACKAGE_PIN Y16 [get_ports i_button]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets i_scl_IBUF]

# Ensure that reset is zero
set_property PULLDOWN true [get_ports i_rst]